name: Auto-Merge Manifest

on:
    workflow_call:
        secrets:
            rdkcentral_token:
                required: true
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bhc-auto-merge')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Auto-merge PR
        run: |
          echo "Automatically merging PR #${{ github.event.pull_request.number }}"
          # Set up Git to push
            git config user.name "${{ vars.rdkcentral_ACCOUNT_USERNAME }}"
            git config user.email "${{ vars.rdkcentral_ACCOUNT_EMAIL }}"
          # Merge the PR
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
