name: Merge PRs linked to Issue
on:
  workflow_call:
    inputs:
      issueNumber:
        description: 'Issue Number to fetch linked PRs'
        required: true
        type: string
    secrets:
      RDKCM_RDKE:
        required: true

jobs:
  merge_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build_tools_workflows code
      uses: actions/checkout@v4
      with:
        repository: rdkcentral/build_tools_workflows
        path: 'tools'
        ref: develop
        token: ${{ secrets.RDKCM_RDKE }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install requests

    - name: Merge Pull Requests
      env:
        GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
        GITHUB_ORG: 'rdkcentral'
        ISSUE_NUMBER: ${{ github.event.inputs.issueNumber }}
        REPO_NAME: ${{ github.repository }}
      run: |
        python3 tools/build_health_check_issues_topic_scripts/merge_prs_for_issue.py ${{ github.event.inputs.issueNumber }} ${{ github.repository }}
