name: Fossid Pre-merge Stateless Diff Scan

on:
  workflow_call:
    inputs:
      base_ref:
        description: 'Base ref for diff (for example develop)'
        required: true
        type: string
      compare_ref:
        description: 'Head SHA to compare against'
        required: true
        type: string
      pr_number:
        description: 'PR number used to fetch the head ref'
        required: true
        type: string
    secrets:
      FOSSID_CONTAINER_USERNAME:
        required: true
      FOSSID_CONTAINER_PASSWORD:
        required: true
      FOSSID_HOST_USERNAME:
        required: true
      FOSSID_HOST_TOKEN:
        required: true

jobs:
  run-diffscan:
    name: Fossid Annotate PR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    container:
      image: quay.io/fossid/fossid-toolbox:1.5.29
      credentials:
        username: ${{ secrets.FOSSID_CONTAINER_USERNAME }}
        password: ${{ secrets.FOSSID_CONTAINER_PASSWORD }}

    steps:
      - name: Checkout base repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.base_ref }}
          fetch-depth: 0
          persist-credentials: false
          submodules: false
          lfs: false

      - name: Mark workspace safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Fetch PR head ref
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
        run: git fetch --no-tags origin "pull/$PR_NUMBER/head:pr-head"

      - name: Checkout ignore projects file
        uses: actions/checkout@v5
        with:
          repository: rdkcentral/build_tools_workflows
          sparse-checkout: |
            ignore_projects_fossid
          ref: develop
          path: tools
          persist-credentials: false
          submodules: false
          lfs: false

      - name: Run fossid-toolbox
        env:
          FOSSID_HOST_USERNAME: ${{ secrets.FOSSID_HOST_USERNAME }}
          FOSSID_HOST_TOKEN: ${{ secrets.FOSSID_HOST_TOKEN }}
          BASE_REF: ${{ inputs.base_ref }}
        run: |
          fossid \
            diffscan \
            --fossid-host "$FOSSID_HOST_USERNAME" \
            --fossid-token "$FOSSID_HOST_TOKEN" \
            --format github \
            --fail \
            --ignore-projects tools/ignore_projects_fossid \
            --base-ref "origin/$BASE_REF" \
            --compare-ref "pr-head"
