name: Fossid Pre-merge Stateless Diff Scan

on:
  workflow_call:
    secrets:
      FOSSID_CONTAINER_USERNAME:
        required: true
      FOSSID_CONTAINER_PASSWORD:
        required: true
      FOSSID_HOST_USERNAME:
        required: true
      FOSSID_HOST_TOKEN:
        required: true

jobs:
  run-fossid-toolbox:
    name: Fossid Annotate PR
    runs-on: ubuntu-latest
    container:
      image: quay.io/fossid/fossid-toolbox:latest
      credentials:
        username: ${{ secrets.FOSSID_CONTAINER_USERNAME }}
        password: ${{ secrets.FOSSID_CONTAINER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout ignore projects file
        uses: actions/checkout@v4
        with:
          repository: rdkcentral/build_tools_workflows
          sparse-checkout: |
            ignored_projects_list
          ref: feature/new_fossid_ignore_list
          
      - name: Debug fossid-toolbox # adding step to check 
        run: |
          echo "Checking for fossid-toolbox..."
          which fossid-toolbox || echo "fossid Not found"
          
      - name: Run fossid-toolbox
        env:
          FOSSID_HOST_USERNAME: ${{ secrets.FOSSID_HOST_USERNAME }}
          FOSSID_HOST_TOKEN: ${{ secrets.FOSSID_HOST_TOKEN }}
        run: |
          fossid-toolbox \
          diff-scan \
          --fossid-host $FOSSID_HOST_USERNAME \
          --fossid-token $FOSSID_HOST_TOKEN \
          --github-workflow-errors \
          --fail-on-any-issues 1 \
          --ignore-projects ignored_projects_list
